tools:
    php_code_coverage:
        enabled:              false
        test_command:         phpunit


    # Code Sniffer
    php_code_sniffer:
        enabled:              true
        command:              phpcs
        config:
            standard:         PSR2


    # Copy/Paste Detector
    php_cpd:
        enabled:              true
        command:              phpcpd


    # Analyzes the size and structure of a PHP project.
    php_loc:
        enabled:              true
        command:              phploc


    # PHP Mess Detector (http://phpmd.org).
    php_mess_detector:
        enabled:              true
        command:              phpmd
        config:
            rulesets:
                - codesize
                - unusedcode
                - naming
                - design


    # Analyzes the size and structure of a PHP project.
    php_pdepend:
        enabled:              true
        command:              pdepend

    # Runs Scrutinizer's PHP Analyzer Tool
    php_analyzer:
        enabled:              true

    # Security Advisory Checker
    sensiolabs_security_checker: true
