language: php
php:
 - "5.4"
 - "5.3"
before_script: 
 - pyrus install pear.phpunit.de/DbUnit
 - pecl install memcache
 - echo "extension=memcache.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
 
services:
  memcached

script: phpunit --configuration tests/config.xml
 
