language: php
php:
 - "5.4"
 - "5.3"
before_script: 
 - pyrus install pear.phpunit.de/DbUnit
 - wget http://pecl.php.net/get/memcache-2.2.6.tgz
 - tar -xzf memcache-2.2.6.tgz
 - sh -c "cd memcache-2.2.6 && phpize && ./configure --enable-memcache && make && sudo make install"
 - echo "extension=memcache.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
 - psql -c 'create database ntentan_tests;' -U postgres
 - psql -f tests/databases/postgresql.sql -U postgres -d ntentan_tests
 - mysql -e 'create database ntentan_tests;'
 - mysql ntentan_tests < tests/databases/mysql.sql
 - mkdir tests/tmp
 
services:
 - memcached
 - mysql
 - postgresql

script: phpunit --configuration tests/travis_config.xml
 
