language: php
php:
 - "5.4"
 - "5.3"
before_script: 
 - pyrus install pear.phpunit.de/DbUnit
 - pecl install memcached
 - echo "extension=memcached.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
 
script: phpunit --configuration tests/config.xml
 
