language: php
php:
 - "5.4"
 - "5.5"
 - "hhvm"
 
matrix:
  allow_failures:
   - php: "7"
  include:
   - php: "5.6"
     env: COVERAGE=yes   
     
before_script:
 - composer install --prefer-dist     

script: vendor/bin/phpunit --coverage-clover coverage.clover tests/cases
after_script: if [ "$COVERAGE" == "yes" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

